<a href="https://colab.research.google.com/github/Thanaphon-673020253-2/PythonDataViz2026/blob/main/pythondataviz_hw_673020253_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Hw3

## HW คำนวณเวลาเป็นวินาทีของเวลาต่อไปนี้โดยใช้คำสั่ง split() ช่วย (print ออกมาให้สวยงาม)
12:30:15

13:41:07

12:53:15

00:59:25

11:11:11

16:06:09

In [ ]:
print("=============================================================")
time = '12:30:15'
t = time.split(':')
h = int(t[0])
m = int(t[1])
se = int(t[2])
total_se = (h * 3600) + (m * 60) + se
print(f"เวลา {time} คิดเป็น {total_se:,} วินาที")

print("=============================================================")
time = '13:41:07'
t = time.split(':')
h = int(t[0])
m = int(t[1])
se = int(t[2])
total_se = (h * 3600) + (m * 60) + se
print(f"เวลา {time} คิดเป็น {total_se:,} วินาที")
print("=============================================================")

time = '12:53:15'
t = time.split(':')
h = int(t[0])
m = int(t[1])
se = int(t[2])
total_se = (h * 3600) + (m * 60) + se
print(f"เวลา {time} คิดเป็น {total_se:,} วินาที")
print("=============================================================")
time = '00:59:25'
t = time.split(':')
h = int(t[0])
m = int(t[1])
se = int(t[2])
total_se = (h * 3600) + (m * 60) + se
print(f"เวลา {time} คิดเป็น {total_se:,} วินาที")
print("=============================================================")
time = '11:11:11'
t = time.split(':')
h = int(t[0])
m = int(t[1])
se = int(t[2])
total_se = (h * 3600) + (m * 60) + se
print(f"เวลา {time} คิดเป็น {total_se:,} วินาที")
print("=============================================================")
time = '16:06:09'
t = time.split(':')
h = int(t[0])
m = int(t[1])
se = int(t[2])
total_se = (h * 3600) + (m * 60) + se
print(f"เวลา {time} คิดเป็น {total_se:,} วินาที")
print("=============================================================")

=============================================================
เวลา 12:30:15 คิดเป็น 45,015 วินาที
=============================================================
เวลา 13:41:07 คิดเป็น 49,267 วินาที
=============================================================
เวลา 12:53:15 คิดเป็น 46,395 วินาที
=============================================================
เวลา 00:59:25 คิดเป็น 3,565 วินาที
=============================================================
เวลา 11:11:11 คิดเป็น 40,271 วินาที
=============================================================
เวลา 16:06:09 คิดเป็น 57,969 วินาที
=============================================================

## ให้สร้างฟังก์ชั่นคำนวณเวลาเป็นวินาทีของเวลาใดๆ และ print ออกมาให้สวยงาม

In [ ]:
def counting_seconds(time):
    t = time.split(':')
    h = int(t[0])
    m = int(t[1])
    se = int(t[2])
    total_second = (h * 3600) + (m * 60) + se
    print(f"เวลา {time} ชั่วโมง คิดเป็น {total_second:,} วินาที")

## ให้ สร้าง list ของ เวลา ```['12:30:15','13:41:07',....]``` แล้ววนลูปเรียกฟังก์ชั่นคำนวณเวลาเป็น วินาที

**commit ว่า HW3**

In [ ]:
time_list = [
    "12:30:15",
    "13:41:07",
    "12:53:15",
    "00:59:25",
    "11:11:11",
    "16:06:09"]

In [ ]:
print(f'<-------แปลงเวลา(ชั่วโมง) เป็นวินาที------->')
for i in time_list:
    counting_seconds(i)

<-------แปลงเวลา(ชั่วโมง) เป็นวินาที------->
เวลา 12:30:15 ชั่วโมง คิดเป็น 45,015 วินาที
เวลา 13:41:07 ชั่วโมง คิดเป็น 49,267 วินาที
เวลา 12:53:15 ชั่วโมง คิดเป็น 46,395 วินาที
เวลา 00:59:25 ชั่วโมง คิดเป็น 3,565 วินาที
เวลา 11:11:11 ชั่วโมง คิดเป็น 40,271 วินาที
เวลา 16:06:09 ชั่วโมง คิดเป็น 57,969 วินาที

#Hw4

## HW
#### เขียน function ตัดเกรด โดยที่ input เป็นคะแนน(0-100) , output เป็นเกรด (F-A)
#### วนลูปตัดเกรด input = [1,50,65,90,101,-5,49]

##### กำหนด
      ถ้าคะแนนอยู่ระหว่างมากกว่าหรือเท่ากับ  0  แต่น้อยกว่า 50 จะได้เกรด F
      ถ้าคะแนนอยู่ระหว่างมากกว่าหรือเท่ากับ 50 แต่น้อยกว่า 55 จะได้เกรด D
      ถ้าคะแนนอยู่ระหว่างมากกว่าหรือเท่ากับ 55 แต่น้อยกว่า 60 จะได้เกรด D+
      ถ้าคะแนนอยู่ระหว่างมากกว่าหรือเท่ากับ 60 แต่น้อยกว่า 65 จะได้เกรด C
      ถ้าคะแนนอยู่ระหว่างมากกว่าหรือเท่ากับ 65 แต่น้อยกว่า 70 จะได้เกรด C+
      ถ้าคะแนนอยู่ระหว่างมากกว่าหรือเท่ากับ 70 แต่น้อยกว่า 75 จะได้เกรด B
      ถ้าคะแนนอยู่ระหว่างมากกว่าหรือเท่ากับ 75 แต่น้อยกว่า 80 จะได้เกรด B+
      ถ้าคะแนนอยู่ระหว่างมากกว่าหรือเท่ากับ 80  จะได้เกรด A
      แต่ว่าค่าคะแนนจะต้องไม่ต่ำกว่า 0 และมากกว่า 100 ไม่งั้นจะเกิด error

In [ ]:
def grade(score):
    if score > 100:
        return "Error"
    elif score < 0:
        return "Error"
    elif score >= 80:
        return "A"
    elif score >=75:
        return "B+"
    elif score >= 70:
        return "B"
    elif score >= 60:
        return "C+"
    elif score >= 60:
        return "C"
    elif score >= 55:
        return "D+"
    elif score >= 50:
        return "D"
    else:
        return "F"

In [ ]:
score_list = [1,50,65,90,101,-5,49]

In [ ]:
for i in score_list:
    if 0 <= i <= 100:
        score_grade = grade(i)
        print(f"คะแนนคุณคือ {i} คุณได้เกรด {score_grade}")
    else:
        print(f"คะแนนคุณคือ {i} ไม่ถูกต้อง")

คะแนนคุณคือ 1 คุณได้เกรด F
คะแนนคุณคือ 50 คุณได้เกรด D
คะแนนคุณคือ 65 คุณได้เกรด C+
คะแนนคุณคือ 90 คุณได้เกรด A
คะแนนคุณคือ 101 ไม่ถูกต้อง
คะแนนคุณคือ -5 ไม่ถูกต้อง
คะแนนคุณคือ 49 คุณได้เกรด F

#Hw5

เขียน function คูณ matrix

แล้ว test กับ matrix ขนาด (2,3) * (3,2), (4,4) * (4,1), (2,2) * (2,2)

In [94]:
import numpy as np

In [95]:
def matric_multi(A,B):
    m = len(A)          # จำนวนแถว A
    a = len(A[0])     # จำนวนหลัก A
    b = len(B)        # จำนวนแถว B
    n = len(B[0])       # จำนวนหลัก B
    C = np.zeros((m,n))
    for i in range(m):
        for j in range(n):
            for sum in range(a):
                C[i,j] = C[i,j] + A[i,sum] * B[sum,j]
    return C

In [96]:
A = np.array([[14, 12, 13],[18, 15, 13]]) # ตัวอย่างชุดตัวเลข
B = np.array([[17, 19],[14, 12],[16, 17]])
matric_multi(A, B)

array([[614., 631.],
       [724., 743.]])

In [ ]:
A = np.array([[4, 5, 7, 14],[12, 3, 14, 9],[3, 6, 11, 17],[11, 8, 5, 16]]) # ตัวอย่างชุดตัวเลข
B = np.array([[2],[4],[6],[8]])
matric_multi(A, B)

array([[182.],
       [192.],
       [232.],
       [212.]])

In [ ]:
A = np.array([[4, 16],[11, 24]]) # ตัวอย่างชุดตัวเลข
B = np.array([[7, 8],[9, 47]])
matric_multi(A, B)

array([[ 172.,  784.],
       [ 293., 1216.]])

#Hw6

##HW (ให้ใช้เฉพาะที่อาจารย์สอนไปแล้วในวิชานี้)

1.   คำนวณ อายุเฉลี่ย ของผู้หญิง และผู้ชาย ของข้อมูลทั้งหมด
2.   คำนวณ อายุเฉลี่ย ของผู้หญิง และผู้ชาย ของผู้ป่วยในจังหวัดขอนแก่น
3. หาจำนวนผู้ป่วยที่เป็นคน "**คนต่างชาติเดินทางมาจากต่างประเทศ**"

In [97]:
import pandas as pd
import numpy as np

In [98]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [99]:
df = pd.read_csv("/content/drive/MyDrive/DataVz/confirmed-cases.csv")

/tmp/ipykernel_1826/2868352268.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/content/drive/MyDrive/DataVz/confirmed-cases.csv")

##1.   คำนวณ อายุเฉลี่ย ของผู้หญิง และผู้ชาย ของข้อมูลทั้งหมด

In [100]:
df.head()

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,1,12/1/2020,NaN,หญิง,61.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
1,2,17/1/2020,NaN,หญิง,74.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
2,3,22/1/2020,NaN,หญิง,73.0,ปี,Thailand,นครปฐม,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง
3,4,22/1/2020,NaN,ชาย,68.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN
4,5,24/1/2020,NaN,หญิง,66.0,ปี,China,นนทบุรี,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,NaN

In [10]:
df.columns

Index(['No.', 'announce_date', 'Notified date', 'sex', 'age', 'Unit',
       'nationality', 'province_of_isolation', 'risk', 'province_of_onset',
       'district_of_onset'],
      dtype='object')

In [101]:
df= df.fillna(value={'sex':'ไม่รู้', 'age':-1, 'province_of_isolation':'ไม่รู้', 'nationality':'ไม่รู้', 'district_of_onset': 'ไม่รู้', 'Notified date': '-', 'Unit': 'ปี'})

In [102]:
male = df[df['sex'] == 'ชาย'][['sex','age','province_of_isolation']]
female = df[df['sex'] == 'หญิง'][['sex','age','province_of_isolation']]
male.head()
female.head()

    sex   age province_of_isolation
0  หญิง  61.0         กรุงเทพมหานคร
1  หญิง  74.0         กรุงเทพมหานคร
2  หญิง  73.0                นครปฐม
4  หญิง  66.0               นนทบุรี
5  หญิง  33.0         กรุงเทพมหานคร

In [106]:
male['age'] = pd.to_numeric(male['age'], errors='coerce')
female['age'] = pd.to_numeric(female['age'], errors='coerce')

In [108]:
print(male['age'].mean())
print(female['age'].mean())

34.96292702130938
36.16090881617699

OR

In [109]:
sum = 0
N = 0
for i in male['age']:
  if i > -1:
    sum = sum + i
    N = N + 1
print(sum/N)

34.962927021309376

In [110]:
sum = 0
N = 0
for i in female['age']:
  if i > 0:
    sum = sum + i
    N = N + 1
print(sum/N)

36.16090881617699

## 2.   คำนวณ อายุเฉลี่ย ของผู้หญิง และผู้ชาย ของผู้ป่วยในจังหวัดขอนแก่น

In [111]:
print(male.head())
female.head()

    sex   age province_of_isolation
3   ชาย  68.0         กรุงเทพมหานคร
8   ชาย  63.0         กรุงเทพมหานคร
10  ชาย  33.0         กรุงเทพมหานคร
11  ชาย  61.0         กรุงเทพมหานคร
12  ชาย   6.0         กรุงเทพมหานคร

    sex   age province_of_isolation
0  หญิง  61.0         กรุงเทพมหานคร
1  หญิง  74.0         กรุงเทพมหานคร
2  หญิง  73.0                นครปฐม
4  หญิง  66.0               นนทบุรี
5  หญิง  33.0         กรุงเทพมหานคร

In [120]:
male[male['province_of_isolation'] == "ขอนแก่น"]['age'].mean()

np.float64(34.88742916022669)

In [119]:
female[female['province_of_isolation'] == "ขอนแก่น"]['age'].mean()

np.float64(34.54574132492114)

Or

In [123]:
sum = 0
N = 0
for i in male[male['province_of_isolation'] == "ขอนแก่น"]['age']:
  if i > 0:
    sum = sum + i
    N = N + 1
print(sum/N)

34.88742916022669

In [121]:
sum = 0
N = 0
for i in female[female['province_of_isolation'] == "ขอนแก่น"]['age']:
  if i > 0:
    sum = sum + i
    N = N + 1
print(sum/N)

34.54574132492114

## 3. หาจำนวนผู้ป่วยที่เป็นคน "**คนต่างชาติเดินทางมาจากต่างประเทศ**"

In [124]:
df.head()

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,1,12/1/2020,-,หญิง,61.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่รู้
1,2,17/1/2020,-,หญิง,74.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่รู้
2,3,22/1/2020,-,หญิง,73.0,ปี,Thailand,นครปฐม,คนต่างชาติเดินทางมาจากต่างประเทศ,นครปฐม,เมือง
3,4,22/1/2020,-,ชาย,68.0,ปี,China,กรุงเทพมหานคร,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่รู้
4,5,24/1/2020,-,หญิง,66.0,ปี,China,นนทบุรี,คนต่างชาติเดินทางมาจากต่างประเทศ,กรุงเทพมหานคร,ไม่รู้

In [125]:
len(df[df['nationality'] != "Thailand"])

188260

#Hw7

##สร้างตารางใหม่ ที่ค่าใน ```sex``` เป็น missing ทั้งหมด  
* สรุปว่าทำไม record นั้นๆถึงเป็น missing

In [127]:
import pandas as pd
import numpy as np

In [132]:
df = pd.read_csv("/content/drive/MyDrive/DataVz/confirmed-cases.csv")

/tmp/ipykernel_1826/2868352268.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/content/drive/MyDrive/DataVz/confirmed-cases.csv")

In [137]:
sex_miss = df[df['sex'].isna()]

In [140]:
sex_miss.head()

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
4397,4398,20/12/2020,NaN,NaN,NaN,NaN,Burma,สมุทรสาคร,Cluster สมุทรสาคร,สมุทรสาคร,เมือง
4398,4399,20/12/2020,NaN,NaN,NaN,NaN,Burma,สมุทรสาคร,Cluster สมุทรสาคร,สมุทรสาคร,เมือง
4399,4400,20/12/2020,NaN,NaN,NaN,NaN,Burma,สมุทรสาคร,Cluster สมุทรสาคร,สมุทรสาคร,เมือง
4400,4401,20/12/2020,NaN,NaN,NaN,NaN,Burma,สมุทรสาคร,Cluster สมุทรสาคร,สมุทรสาคร,เมือง
4401,4402,20/12/2020,NaN,NaN,NaN,NaN,Burma,สมุทรสาคร,Cluster สมุทรสาคร,สมุทรสาคร,เมือง

สรุป น่าจะเกิดจากการเก็บข้อมูลไม่ครบถ่วน กรอบข้อมูลไม่ครบ